blank_issues_enabled: true
contact_links:
  - name: wentuno Core Security Policy
    url: https://github.com/wentuno/wentuno/blob/master/SECURITY.md
    about: View security policy
  - name: wentuno Core Developers
    url: https://wentunocore.org
    about: wentuno Core homepage
